bot:
  token: ${DISCORD_BOT_TOKEN}
  client_id: ${DISCORD_CLIENT_ID}
  status: "[TESTING] 読み上げBot"
  owner: ${DISCORD_OWNER_ID:-123456789012345678}

voicevox:
  max_chars: 200
  max_message_length: 50
  host: ${VOICEVOX_HOST:-http://voicevox:50021}

redis:
  host: ${REDIS_HOST:-redis}
  port: ${REDIS_PORT:-6379}
  db: ${REDIS_DB:-0}

